### PR TITLE
retry in case of empty response while fetching resource

### PR DESCRIPTION
**Pull request by harshavmb**
This PR is an additional `retry` function with `azapi_resource` data provider. 

The use case for this `retry` logic is that we have few Azure policies to update DNS configuration of `private endpoints` created by various users. There is some slight delay between the private endpoint resource creation & the Azure policy to create A-record & update the private endpoint DNS configuration. We have seen the time lag of up to 30-40 seconds. 

Currently, we are using either `null_resource` & `sleep` providers. We wait deliberately for certain time expecting the configuration to be updated. Nevertheless, it's not a clean solution. We create inherent dependency on `az-cli`.

With this `retry` logic, `azapi_resource` data provider retries until non empty response is returned by the Azure API. 

I know retrying bluntly on empty response isn't wise but I'm open to your suggestions.

### CODE REVIEW

**Comment by harshavmb** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by harshavmb** [comment]
Hi,

Any update on this PR?

**Comment by ms-henglu** [comment]
Hi @harshavmb ,

Thank you so much for taking time to work on this feature! And apologize for the late response.

We'll think about this feature request and improve it.

**Comment by ms-henglu** [comment]
We received a related feature request: https://github.com/Azure/terraform-provider-azapi/issues/372

**Comment by harshavmb** [comment]
Hi @ms-henglu ,

I'm afraid the feature request you linked isn't the one this PR is about. It's not the resource, it's a data provider. 
As I explained in the PR description, the create part is handled by Azure policies which have few seconds of latency & with data providers we would like to retry until the ARM resource is created by the policy.

**Comment by matt-FFFFFF** [comment]
Although, it might be a different scenario if the API does not return an error (which, I think it should)

**Comment by harshavmb** [comment]
Hi @matt-FFFFFF ,

Indeed if you prefer to have a common function, both resources & data sources could use that but I would like to have this available with data sources too as we have different use-cases than the one mentioned in #372.

**Comment by MatLambethMS** [comment]
Hi folks. How is this one looking? This feature would be extremely useful and looks like a lot of the hard work has been done.

**Comment by ms-henglu** [comment]
Hi @harshavmb ,

Thank you for taking time to open this PR, but the would be solved by https://github.com/Azure/terraform-provider-azapi/pull/392 which supports customized retry error, please subscribe https://github.com/Azure/terraform-provider-azapi/pull/392 for latest updates.

I'll close this PR, but feel free to reopen it if there's any question.

**Pull request closed without merging**
