### PR TITLE
support for the `ignore_changes` feature

### PR DESCRIPTION
**Pull request by ms-henglu**
fixes https://github.com/Azure/terraform-provider-azapi/issues/315

### CODE REVIEW

**Comment by ms-henglu** [comment]
another related issue: https://github.com/Azure/terraform-provider-azapi/issues/219

**Review by magodo — APPROVED** [review]

**Comment by ZachTB123** [comment]
@ms-henglu Does this work with an object's properties inside an array. Like with #219 , I need to ignore the image for a Container App. The body for that resource looks like:

```json
{
  "properties": {
    "template": {
      "containers": [
        {
          "image": "image-here"
        }
      ]
    }
  }
}
```

Using

```hcl
ignore_body_changes = [
  "properties.template.containers[0].image"
]
```

Doesn't seem to work.

**Comment by ms-henglu** [comment]
Hi @ZachTB123 , yes, this field does not work with  an object's properties inside an array. 

How about `ignore_body_changes = [ "properties.template.containers"]`?

**Comment by ms-henglu** [comment]
Hi @adelinn ,

I added more details here: https://github.com/Azure/terraform-provider-azapi/issues/315#issuecomment-1716943998

If your scenario are not included, would you please open an issue and share us more details? Thanks!

**Pull request merged**
