### PR TITLE
Microsoft.Dashboard/grafana

### PR DESCRIPTION
**Pull request by arindam0310018**
Terraform AZAPI code for Microsoft.Dashboard/grafana with ReadMe - https://github.com/arindam0310018/20-Oct-2022-DevOps__Create-Azure-Managed-Grafana-with-Terraform-AZAPI

### CODE REVIEW

**Comment by arindam0310018** [comment]
Hello,
I agree to the below option under Contributor License Agreement (CLA) -

@microsoft-github-policy-service agree
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

Many Thanks
Regards, Arindam Mitra

**Comment by arindam0310018** [comment]
Hello, 
I agreed to the CLA last week.
Please check my comment above.
 
Is there any thing pending from my side for the PR to be merged and completed ? 

Please let me know

Many Thanks
Regards, Arindam Mitra

**Review by ms-henglu — CHANGES_REQUESTED** [review]
Hi @arindam0310018 ,

Thank you so much for contributing this!

This is a great example with many details. But the examples are used to demonstrate how to use azapi resources with azurerm provider, so we want to keep it simple.

Would you please remove azure pipeline file and flatten the variables into one `main.tf`?

Thanks!

**Comment by arindam0310018** [comment]
Hello @ms-henglu 
Apologies for the delayed response.
As requested, I have done below:-
- Deleted Az devops Pipeline, Readme file, variables.tf, tfvars file.
- Merged all into main.tf file.

Request you to review. if all found okay, may I ask to please accept the PR, merge and close.

Many Thanks
regards, Arindam Mitra

**Review by ms-henglu — APPROVED** [review]
Thank you for taking time to make this PR! LGTM!

**Pull request merged**
