### PR TITLE
fix: get after put

### LINKED ISSUE #618: 2.0 beta: Error: Missing Resource State After Create
Hi @ms-henglu I am getting this error on a plan to deploy 378 resources.

This is the sample code: <https://registry.terraform.io/modules/Azure/avm-ptn-alz/azurerm/latest/examples/default>

```
Microsoft.Management/managementGroups/landingzones/providers/Microsoft.Authorization/roleAssignments/4eb5e902-cf89-5342-9592-d66dfcfaee49]
╷
│ Error: Missing Resource State After Create
│ 
│   with module.alz_architecture.azapi_resource.role_definitions["alzroot/Security-Operations"],
│   on ../../main.role_definitions.tf line 1, in resource "azapi_resource" "role_definitions":
│    1: resource "azapi_resource" "role_definitions" {
│ 
│ The Terraform Provider unexpectedly returned no resource state after having no errors in the resource creation. This is always an issue in the
│ Terraform Provider and should be reported to the provider developers.
│ 
│ The resource may have been successfully created, but Terraform is not tracking it. Applying the configuration again with no other action may
│ result in duplicate resource errors. Import the resource if the resource was actually created and Terraform should be tracking it.
```

I also get some other resources getting created but not in state..

```
╷
│ Error: Resource already exists
│ 
│   with module.alz_architecture.azapi_resource.role_definitions["alzroot/Subscription-Owner"],
│   on ../../main.role_definitions.tf line 1, in resource "azapi_resource" "role_definitions":
│    1: resource "azapi_resource" "role_definitions" {
│ 
│ A resource with the ID
│ "/providers/Microsoft.Management/managementGroups/alzroot/providers/Microsoft.Authorization/roleDefinitions/402344ce-48c4-5ac1-9320-16726050f964"
│ already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azapi_resource" for more information.
```

Should I enable provider debugging and report back?

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
Modifies retry client to test for status codes and callback funcs on the data interface{}.

CreateUpdate modified  to use this a specific retry client for the get that follows the put.

* Fixes #618

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
@ms-henglu please could you review?

**Comment by ms-henglu** [comment]
I believe this PR also fixes https://github.com/Azure/terraform-provider-azapi/issues/587?

**Review by ms-henglu — COMMENTED** [review]
Thanks @matt-FFFFFF for the PR! LGTM. Just one minor comment, would you please also implement this feature in the data plane client: https://github.com/Azure/terraform-provider-azapi/blob/main/internal/clients/data_plane_client.go#L30

**Comment by matt-FFFFFF** [comment]
Hi @ms-henglu this is ready for another review now - thank you

**Review by ms-henglu — APPROVED** [review]
LGTM！

**Pull request merged**
