### PR TITLE
bugfix: ordering locks to avoid deadlock

### PR DESCRIPTION
**Pull request by ms-henglu**
Fixes https://github.com/Azure/terraform-provider-azapi/issues/672

### CODE REVIEW

**Review by magodo — COMMENTED** [review]
Isn't this a user error?

**Comment by ms-henglu** [comment]
> Isn't this a user error?

Yes, it could be fixed by the user input. But I think the user might not understand why it's necessary to sort the locked resource IDs.

**Review by magodo — COMMENTED** [review]
I'd suggest we change it to be a set if we want to reorder for the users, and mention this in the document.

**Comment by ms-henglu** [comment]
Maybe not necessary to make it a breaking change, because we only use it in a sorted order.

**Review by magodo — APPROVED** [review]

**Pull request merged**
